Bug 1825092 - Pulsebot should comment the changeset hash of the landed changesets to the bug for uplift landings
mozilla-conduit/pulsebot pull request #39
Opened 2023-05-28 22:30 UTC by dklawren

* Added new config for BUGZILLA_UPLIFT which lists repos which are considered to be uplift repos and the comments should be different for pushlogs on those branches.
* Update bugzilla.py utility methods to use the new custom API endpoint for Lando/Pulsebot which allows updating comment tags when creating comments. As well as to be able to update private bugs.
* Update test cases to test for uplift comments
* Removed unused code, create_messages(), and related test code.

2023-05-31 21:11 UTC, cgsheeh requested changes
There are some black formatting changes that need to be applied.

2023-05-31 21:11 UTC, cgsheeh commented on docker-compose.yml
> +      - BUGZILLA_UPLIFT=releases/mozilla-release,releases/mozilla-beta,releases/mozilla-esr
These variables are just for testing, right? If they're the actual values passed to Pulsebot in production, the esr repo needs to be `releases/mozilla-esr102`.

2023-05-31 21:11 UTC, cgsheeh commented on pulsebot/pulse_dispatch.py
> +                    comments_string += c.get("text", "") + "\n"
You build the `comments_string` but only use it to check if `url[-12:] not in comments_string` down the line. Instead you should keep `comments` as a list and then change the check to be `if not any(url[-12:] in comment for comment in comments):`.

2023-05-31 21:11 UTC, cgsheeh commented on pulsebot/pulse_dispatch.py
> +            for cs in info:
Nit: I think `cs_info` is a better variable name here.

2023-06-01 16:13 UTC, dklawren commented on docker-compose.yml
> +      - BUGZILLA_UPLIFT=releases/mozilla-release,releases/mozilla-beta,releases/mozilla-esr
Right. Cloud Ops keeps a separate config separate from the docker-compose so I will need to give them the real values once this rolled out.

2023-06-02 15:05 UTC, cgsheeh approved these changes
LGTM! :tada:

2023-06-02 20:09 UTC, merged